# Stage 1: Build the React app
FROM node:16 as build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Build the React app
RUN npm run build

# Stage 2: Serve the React app
FROM nginx:1.21

# Copy the build files from the build stage to the nginx server
COPY --from=build /app/dist /usr/share/nginx/html

# Copy the nginx configuration file
COPY default.conf /etc/nginx/conf.d/default.conf

# Pass environment variables (if needed)
ARG API_KEY
ENV REACT_APP_API_KEY=$API_KEY


# Expose port 80 (or any other port you want to use)
EXPOSE 80

# Start the nginx server
CMD ["nginx", "-g", "daemon off;"]
