# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Install pkg-config, libmysqlclient-dev, and other dependencies
RUN apt-get update && \
    apt-get install -y pkg-config default-libmysqlclient-dev build-essential

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Upgrade pip
RUN pip install --no-cache-dir --upgrade pip

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application into the container
COPY . .

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
