apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml   # <-- This ensures the namespace exists before deploying other resources
  - twc-fe-service.yaml
  - twc-fe-deployment.yaml
  - twc-fe-secrets.yaml
  - twc-be-deployment.yaml
  - twc-be-service.yaml
namespace: twitterclone