apiVersion: v1
kind: Service
metadata:
  name: twc-be-service
spec:
  selector:
    app: twc-be
  ports:
    - protocol: TCP
      port: 8000  # Port exposed within the cluster
      targetPort: 8000  # Port the container is listening on
  type: ClusterIP 

