apiVersion: v1
kind: Service
metadata:
  name: twc-fe-service
spec:
  selector:
    app: twc-fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  # Match the container's port
  type: ClusterIP  # Will be exposed internally only
